In [1]:
import pandas as pd

In [12]:
import lib.corcoordinate_caculate as cc

In [42]:
near_fac = pd.read_excel('../../all_data/比鄰設施_final表.xlsx')

In [ ]:
# latitude緯度，longitude經度
# Longitude, Latitude錯置整理(白癡寫法)

# 把錯置的取出並轉正常
near_fac_fix = near_fac[ near_fac['Longitude'] > 100]
near_fac_fix.columns
near_fac_fix = near_fac_fix.rename(columns={'機關名稱':'機關名稱', '機關地址':'機關地址', 'Longitude':'Latitude', 'Latitude':'Longitude', '類型':'類型', 'cor':'cor'})
near_fac_fix = near_fac_fix.reindex(columns=['機關名稱', '機關地址', 'Longitude', 'Latitude', '類型'])

# 原先正常的
near_fac_normal = near_fac[ near_fac['Longitude'] < 100]

# 最後再合起來
near_fac = pd.concat([near_fac_normal, near_fac_fix])

In [59]:
cc.convert_lat_lon_to_tuple(near_fac, 'Longitude', 'Latitude')

In [67]:
near_fac[ near_fac['類型'] == '藝文' ]

,機關名稱,機關地址,Longitude,Latitude,類型,cor
12750,國立故宮博物院,台北市士林區至善路二段二二一號,25.102839,121.553232,藝文,"(25.1028387, 121.5532316)"
12751,國立國父紀念館,台北市信義區仁愛路四段五0五號,25.037678,121.557755,藝文,"(25.0376784, 121.5577551)"
12752,國立教育廣播電臺,台北市南海路41號,25.031897,121.512429,藝文,"(25.0318971, 121.5124292)"
12753,國立歷史博物館,台北市南海路49號,25.031454,121.511227,藝文,"(25.031454, 121.511227)"
12754,國家人權博物館籌備處,新北市新店區復興路131號,24.988101,121.532272,藝文,"(24.9881013, 121.5322721)"
12755,臺北縣立十三行博物館,臺北縣八里鄉博物館路200號,25.157684,121.404840,藝文,"(25.1576837, 121.4048398)"
12756,臺北縣立淡水古蹟博物館,台北縣淡水鎮中正路28巷1號,25.175330,121.433455,藝文,"(25.1753301, 121.4334555)"
12757,臺北縣立鶯歌陶瓷博物館,臺北縣鶯歌鎮文化路200號,24.949251,121.352032,藝文,"(24.949251, 121.352032)"
12758,臺北市青少年發展處,臺北市中正區仁愛路一段17號,25.039138,121.522266,藝文,"(25.0391377, 121.5222662)"
12759,臺北市家庭教育中心,臺北市吉林路110號5樓,25.053630,121.529891,藝文,"(25.0536299, 121.5298914)"
12760,臺北縣立十三行博物館籌備處,臺北縣八里鄉頂罟村信義路一八六號,25.156676,121.402841,藝文,"(25.156676, 121.402841)"
12761,國立臺灣民主紀念館,台北市中正區中山南路21號,25.036960,121.519442,藝文,"(25.0369599, 121.5194421)"
12762,臺北市立兒童育樂中心,臺北市中山區中山北路3段66號,25.072760,121.523966,藝文,"(25.0727604, 121.5239663)"
12763,臺北市青少年育樂中心,臺北市仁愛路一段一七號,25.038786,121.521557,藝文,"(25.0387861, 121.5215566)"
12764,國家表演藝術中心,臺北市中正區中山南路21-1號,25.037127,121.519336,藝文,"(25.0371269, 121.5193364)"
12765,新北市立鶯歌陶瓷博物館,新北市鶯歌區文化路200號,24.949251,121.352032,藝文,"(24.949251, 121.352032)"
12766,新北市立十三行博物館,新北市八里區博物館路200號,25.157684,121.404840,藝文,"(25.1576837, 121.4048398)"
12767,新北市立淡水古蹟博物館,新北市淡水區中正路1段6巷32-2號,25.176080,121.426708,藝文,"(25.1760796, 121.4267079)"
12768,國家電影及視聽文化中心,台北市中正區青島東路7號4樓,25.043905,121.522320,藝文,"(25.0439054, 121.5223201)"
12769,國家兩廳院,臺北市中正區中山南路21之1號,25.035549,121.518346,藝文,"(25.035549, 121.5183457)"
12770,國立中正紀念堂管理處,臺北市中山南路21號,25.036960,121.519442,藝文,"(25.0369599, 121.5194421)"
12771,臺北市立天文科學教育館,臺北市士林區基河路三六三號,25.091358,121.521514,藝文,"(25.0913579, 121.5215142)"
12772,臺北表演藝術中心,臺北市士林區劍潭路1號,25.085149,121.524367,藝文,"(25.0851489, 121.524367)"
12773,國家鐵道博物館籌備處,臺北市信義區市民大道5段50號,25.047420,121.564697,藝文,"(25.0474196, 121.5646971)"
20636,國立臺灣博物館,臺北市中正區襄陽路2號,25.042745,121.515009,藝文,"(25.0427453, 121.5150091)"
20637,臺北市立兒童交通博物館,台北巿汀州路三段2號,25.020129,121.525326,藝文,"(25.0201295, 121.5253263)"
20638,新北市立黃金博物館,新北市瑞芳區金光路8號,25.106141,121.859663,藝文,"(25.106141, 121.8596634)"
20639,臺北流行音樂中心,臺北市南港區市民大道8段99號,25.052772,121.598316,藝文,"(25.0527719, 121.5983165)"
22099,國立國光劇團,台北市木柵路三段七七號五樓,24.988794,121.568026,藝文,"(24.9887944, 121.5680257)"
22100,臺北縣立黃金博物館,臺北縣瑞芳鎮金光路8號,25.106141,121.859663,藝文,"(25.106141, 121.8596634)"
22571,國立臺灣博物館(981231前使用),台北市襄陽路二號,25.043407,121.515005,藝文,"(25.0434071, 121.5150048)"
3041,國立臺灣科學教育館,NaN,25.096130,121.516690,藝文,"(25.09613, 121.51669)"
3042,國立中正紀念堂,NaN,25.036190,121.518680,藝文,"(25.03619, 121.51868)"
3043,臺北市立美術館,NaN,25.071960,121.524370,藝文,"(25.07196, 121.52437)"
3044,台北當代藝術館,NaN,25.050720,121.518920,藝文,"(25.05072, 121.51892)"
3045,台北探索館,NaN,25.037530,121.563770,藝文,"(25.03753, 121.56377)"
3046,西門紅樓,NaN,25.042070,121.506930,藝文,"(25.04207, 121.50693)"
3047,國立臺灣大學博物館群_醫學人文博物館,NaN,25.039530,121.518860,藝文,"(25.03953, 121.51886)"
3048,國立臺灣博物館_古生物館,NaN,25.043560,121.514360,藝文,"(25.04356, 121.51436)"
3049,臺北植物園,NaN,25.031000,121.508660,藝文,"(25.031, 121.50866)"
3050,國立臺灣藝術教育館,NaN,25.032320,121.512050,藝文,"(25.03232, 121.51205)"
3051,MAJI集食行樂_圓山花博爭豔館,NaN,25.069660,121.521730,藝文,"(25.06966, 121.52173)"
3052,台灣設計館,NaN,25.043700,121.559740,藝文,"(25.0437, 121.55974)"
3053,忠泰美術館,NaN,25.044300,121.537310,藝文,"(25.0443, 121.53731)"

In [62]:
type_list = list(near_fac['類型'].unique())

In [63]:
type_list

['公共活動空間',
 '加油站',
 '幼兒園',
 '托兒所',
 '宗教場所',
 '法院/檢察署',
 '便利商店',
 '發電廠',
 '消防單位',
 '清潔單位',
 '焚化廠',
 '圖書館',
 '銀行',
 '學校',
 '殯儀館',
 '藝文',
 '警局',
 '醫院',
 '療養院',
 '診所',
 '藥局',
 '醫療設施',
 '交流道出入口',
 '捷運出口',
 '商圈']

In [68]:
house_df = pd.read_csv('../../all_data/主資料集/台北市_10101_11303_房價data.csv')

In [69]:
house_df = house_df.head(100)

In [72]:
house_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 31 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Unnamed: 0                     100 non-null    int64
 1   usage_category                 100 non-null    object
 2   address                        100 non-null    object
 3   property_type                  100 non-null    object
 4   community_name                 27 non-null     object
 5   main_building_ratio            97 non-null     float64
 6   city                           100 non-null    object
 7   parking_space_price            6 non-null      float64
 8   transaction_date               100 non-null    object
 9   elevator_available             0 non-null      float64
 10  building_age                   94 non-null     float64
 11  number_of_land                 100 non-null    int64
 12  number_of_building             100 non-null    int64
 13  number_of_parking_space        100 non-null    int64
 14  latitude                       100 non-null    float64
 15  longitude                      100 non-null    float64
 16  management_org_available       100 non-null    int64
 17  per_ping_calculation_method    100 non-null    object
 18  note                           54 non-null     object
 19  price_per_ping                 97 non-null     float64
 20  detailed_usage_classification  100 non-null    object
 21  total_area_ping                100 non-null    float64
 22  property_b_l_p_type            100 non-null    object
 23  district                       100 non-null    object
 24  total_price                    100 non-null    int64
 25  total_floors                   99 non-null     float64
 26  target_floor                   100 non-null    float64
 27  transaction_floors             99 non-null     float64
 28  bedrooms                       89 non-null     float64
 29  living_rooms                   89 non-null     float64
 30  bathrooms                      89 non-null     float64
dtypes: float64(14), int64(6), object(11)
memory usage: 24.3+ KB

In [73]:
cc.convert_lat_lon_to_tuple(house_df, 'latitude', 'longitude')

In [74]:
for fac_type in type_list:
    near_fac_df = near_fac[ near_fac['類型'] == fac_type ]
    cc.distance_caculate_and_cat_counts(house_df ,near_fac_df, fac_type, [250, 500, 750])

In [84]:
house_df.info(max_cols=107)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 107 columns):
 #    Column                         Non-Null Count  Dtype
---   ------                         --------------  -----
 0    Unnamed: 0                     100 non-null    int64
 1    usage_category                 100 non-null    object
 2    address                        100 non-null    object
 3    property_type                  100 non-null    object
 4    community_name                 27 non-null     object
 5    main_building_ratio            97 non-null     float64
 6    city                           100 non-null    object
 7    parking_space_price            6 non-null      float64
 8    transaction_date               100 non-null    object
 9    elevator_available             0 non-null      float64
 10   building_age                   94 non-null     float64
 11   number_of_land                 100 non-null    int64
 12   number_of_building             100 non-null    int64
 13   number_of_parking_space        100 non-null    int64
 14   latitude                       100 non-null    float64
 15   longitude                      100 non-null    float64
 16   management_org_available       100 non-null    int64
 17   per_ping_calculation_method    100 non-null    object
 18   note                           54 non-null     object
 19   price_per_ping                 97 non-null     float64
 20   detailed_usage_classification  100 non-null    object
 21   total_area_ping                100 non-null    float64
 22   property_b_l_p_type            100 non-null    object
 23   district                       100 non-null    object
 24   total_price                    100 non-null    int64
 25   total_floors                   99 non-null     float64
 26   target_floor                   100 non-null    float64
 27   transaction_floors             99 non-null     float64
 28   bedrooms                       89 non-null     float64
 29   living_rooms                   89 non-null     float64
 30   bathrooms                      89 non-null     float64
 31   cor                            100 non-null    object
 32   公共活動空間_under_250_m             100 non-null    float64
 33   公共活動空間_under_500_m             100 non-null    float64
 34   公共活動空間_under_750_m             100 non-null    float64
 35   加油站_under_250_m                100 non-null    float64
 36   加油站_under_500_m                100 non-null    float64
 37   加油站_under_750_m                100 non-null    float64
 38   幼兒園_under_250_m                100 non-null    float64
 39   幼兒園_under_500_m                100 non-null    float64
 40   幼兒園_under_750_m                100 non-null    float64
 41   托兒所_under_250_m                100 non-null    float64
 42   托兒所_under_500_m                100 non-null    float64
 43   托兒所_under_750_m                100 non-null    float64
 44   宗教場所_under_250_m               100 non-null    float64
 45   宗教場所_under_500_m               100 non-null    float64
 46   宗教場所_under_750_m               100 non-null    float64
 47   法院/檢察署_under_250_m             100 non-null    float64
 48   法院/檢察署_under_500_m             100 non-null    float64
 49   法院/檢察署_under_750_m             100 non-null    float64
 50   便利商店_under_250_m               100 non-null    float64
 51   便利商店_under_500_m               100 non-null    float64
 52   便利商店_under_750_m               100 non-null    float64
 53   發電廠_under_250_m                100 non-null    float64
 54   發電廠_under_500_m                100 non-null    float64
 55   發電廠_under_750_m                100 non-null    float64
 56   消防單位_under_250_m               100 non-null    float64
 57   消防單位_under_500_m               100 non-null    float64
 58   消防單位_under_750_m               100 non-null    float64
 59   清潔單位_under_250_m               100 non-null    float64
 60   清潔單位_under_500_m               100 non-null    float64
 61   清潔單位_under_750_m               100 non-null    float64
 62   焚化廠_under_250_m                100 non-null    float64
 63   焚化廠_under_500_m                100 non-null    float64
 64   焚化廠_under_750_m                100 non-null    float64
 65   圖書館_under_250_m                100 non-null    float64
 66   圖書館_under_500_m                100 non-null    float64
 67   圖書館_under_750_m                100 non-null    float64
 68   銀行_under_250_m                 100 non-null    float64
 69   銀行_under_500_m                 100 non-null    float64
 70   銀行_under_750_m                 100 non-null    float64
 71   學校_under_250_m                 100 non-null    float64
 72   學校_under_500_m                 100 non-null    float64
 73   學校_under_750_m                 100 non-null    float64
 74   殯儀館_under_250_m                100 non-null    float64
 75   殯儀館_under_500_m                100 non-null    float64
 76   殯儀館_under_750_m                100 non-null    float64
 77   藝文_under_250_m                 100 non-null    float64
 78   藝文_under_500_m                 100 non-null    float64
 79   藝文_under_750_m                 100 non-null    float64
 80   警局_under_250_m                 100 non-null    float64
 81   警局_under_500_m                 100 non-null    float64
 82   警局_under_750_m                 100 non-null    float64
 83   醫院_under_250_m                 100 non-null    float64
 84   醫院_under_500_m                 100 non-null    float64
 85   醫院_under_750_m                 100 non-null    float64
 86   療養院_under_250_m                100 non-null    float64
 87   療養院_under_500_m                100 non-null    float64
 88   療養院_under_750_m                100 non-null    float64
 89   診所_under_250_m                 100 non-null    float64
 90   診所_under_500_m                 100 non-null    float64
 91   診所_under_750_m                 100 non-null    float64
 92   藥局_under_250_m                 100 non-null    float64
 93   藥局_under_500_m                 100 non-null    float64
 94   藥局_under_750_m                 100 non-null    float64
 95   醫療設施_under_250_m               100 non-null    float64
 96   醫療設施_under_500_m               100 non-null    float64
 97   醫療設施_under_750_m               100 non-null    float64
 98   交流道出入口_under_250_m             100 non-null    float64
 99   交流道出入口_under_500_m             100 non-null    float64
 100  交流道出入口_under_750_m             100 non-null    float64
 101  捷運出口_under_250_m               100 non-null    float64
 102  捷運出口_under_500_m               100 non-null    float64
 103  捷運出口_under_750_m               100 non-null    float64
 104  商圈_under_250_m                 100 non-null    float64
 105  商圈_under_500_m                 100 non-null    float64
 106  商圈_under_750_m                 100 non-null    float64
dtypes: float64(89), int64(6), object(12)
memory usage: 83.7+ KB

In [77]:
house_df.describe()

,Unnamed: 0,main_building_ratio,parking_space_price,elevator_available,building_age,number_of_land,number_of_building,number_of_parking_space,latitude,longitude,...,醫療設施_under_750_m,交流道出入口_under_250_m,交流道出入口_under_500_m,交流道出入口_under_750_m,捷運出口_under_250_m,捷運出口_under_500_m,捷運出口_under_750_m,商圈_under_250_m,商圈_under_500_m,商圈_under_750_m
count,100.000000,97.000000,6.000000,0.0,94.000000,100.000000,100.000000,100.00000,100.000000,100.000000,...,100.000000,100.0,100.0,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.00000
mean,49.500000,76.859897,986.666667,NaN,31.691489,1.500000,1.040000,0.45000,25.102394,121.525769,...,0.170000,0.0,0.0,0.020000,0.140000,0.380000,0.450000,0.050000,0.020000,0.08000
std,29.011492,20.340386,397.777157,NaN,12.677155,1.114641,0.242878,0.96792,0.013046,0.011326,...,0.377525,0.0,0.0,0.140705,0.471833,0.788554,0.998737,0.219043,0.140705,0.27266
min,0.000000,36.140000,450.000000,NaN,1.000000,1.000000,1.000000,0.00000,25.079463,121.501108,...,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000
25%,24.750000,57.890000,667.500000,NaN,26.000000,1.000000,1.000000,0.00000,25.090900,121.521723,...,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000
50%,49.500000,83.660000,1120.000000,NaN,36.000000,1.000000,1.000000,0.00000,25.102397,121.526476,...,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000
75%,74.250000,91.560000,1265.000000,NaN,40.000000,2.000000,1.000000,0.00000,25.110721,121.530971,...,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000
max,99.000000,100.000000,1400.000000,NaN,53.000000,7.000000,3.000000,4.00000,25.145982,121.562979,...,1.000000,0.0,0.0,1.000000,2.000000,3.000000,4.000000,1.000000,1.000000,1.00000

In [86]:
house_df.to_csv('./比鄰程式測試.csv')