In [1]:
import pandas as pd
import numpy as np

In [42]:
time_df = pd.read_csv('../../all_data/house_price_monthly_bfill.csv', encoding='utf-8')

In [43]:
eco_drop_list = [ 'EB22',  'EC06', 'EC07', 'MC31G', 'MC36G', 'NE0812', 'OC08G', '無鉛汽油95']

In [44]:
time_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 159 entries, 0 to 158
Data columns (total 45 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   date                    159 non-null    object
 1   house_index_xyi_all_tp  159 non-null    float64
 2   house_index_xyi_tp      159 non-null    float64
 3   house_index_xyi_new_tp  159 non-null    float64
 4   EA1101                  159 non-null    float64
 5   EB0312                  159 non-null    float64
 6   EB0911                  159 non-null    float64
 7   EB18                    159 non-null    float64
 8   EB21                    159 non-null    float64
 9   EB22                    159 non-null    float64
 10  EC06                    159 non-null    float64
 11  EC07                    159 non-null    float64
 12  LA07                    159 non-null    float64
 13  MA1501                  159 non-null    float64
 14  MB65                    159 non-null    float64
 15  MC31                    159 non-null    float64
 16  MC31G                   159 non-null    float64
 17  MC36                    159 non-null    float64
 18  MC36G                   159 non-null    float64
 19  MO30                    159 non-null    float64
 20  MP101G                  159 non-null    float64
 21  NA0101                  159 non-null    float64
 22  NA1005                  159 non-null    float64
 23  NB0101                  159 non-null    float64
 24  NC0117                  159 non-null    float64
 25  NC0118                  159 non-null    float64
 26  NE0206                  159 non-null    float64
 27  NE0812                  159 non-null    float64
 28  OC08G                   159 non-null    float64
 29  PA0120                  159 non-null    float64
 30  PA1205                  159 non-null    float64
 31  PE0503                  159 non-null    float64
 32  TSE收盤                   159 non-null    float64
 33  水泥(TSE11)收盤             159 non-null    float64
 34  建材營造(TSE25)收盤           159 non-null    float64
 35  航運業(TSE26)收盤            159 non-null    float64
 36  鋼鐵(TSE20)收盤             159 non-null    float64
 37  倫敦鋁現貨價                  159 non-null    float64
 38  倫敦高級銅極現貨價               159 non-null    float64
 39  巴拿馬型貨櫃運費指數              159 non-null    float64
 40  杜拜輕原油現貨價                159 non-null    float64
 41  水泥50kg北區台泥              159 non-null    float64
 42  無鉛汽油95                  159 non-null    float64
 43  竹節鋼筋_南                  159 non-null    float64
 44  預拌混凝土3000磅台北            159 non-null    float64
dtypes: float64(44), object(1)
memory usage: 56.0+ KB

In [45]:
time_df.drop(eco_drop_list, axis=1, inplace=True)

In [46]:
time_df

,date,house_index_xyi_all_tp,house_index_xyi_tp,house_index_xyi_new_tp,EA1101,EB0312,EB0911,EB18,EB21,LA07,...,建材營造(TSE25)收盤,航運業(TSE26)收盤,鋼鐵(TSE20)收盤,倫敦鋁現貨價,倫敦高級銅極現貨價,巴拿馬型貨櫃運費指數,杜拜輕原油現貨價,水泥50kg北區台泥,竹節鋼筋_南,預拌混凝土3000磅台北
0,2011-01-31,95.40,94.45,96.84,34.0,28.8,1.0978,86.78,95.85,4.64,...,347.10,123.49,120.70,2450.300,9560.900,1738.2,91.6700,151.5,21260.0,1815.0
1,2011-02-28,97.69,97.34,98.23,34.0,28.8,1.3261,85.89,96.75,4.69,...,311.73,108.61,117.89,2513.250,9853.125,1696.0,99.7525,151.5,21250.0,1890.0
2,2011-03-31,97.76,97.86,97.61,31.0,28.8,1.3950,83.66,96.60,4.48,...,296.68,103.48,122.54,2548.875,9564.625,2071.5,109.1775,151.5,21525.0,1890.0
3,2011-04-30,97.31,98.38,95.69,29.0,28.8,1.2941,85.78,100.45,4.29,...,315.80,110.02,122.81,2682.700,9524.800,1601.0,115.6840,151.5,20500.0,1896.0
4,2011-05-31,96.85,97.02,96.60,27.0,28.8,1.6650,85.40,102.60,4.27,...,330.61,112.45,118.57,2587.625,8945.125,1755.0,105.4850,151.5,20175.0,1787.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
154,2023-11-30,162.10,150.51,179.66,20.0,42.5,2.8952,69.40,67.42,3.34,...,416.55,138.28,139.30,2197.875,8135.500,1729.0,82.7800,169.5,20250.0,2625.0
155,2023-12-31,163.19,150.85,181.90,22.0,45.4,2.6980,70.06,67.32,3.33,...,430.66,154.46,146.64,2204.900,8450.000,2063.5,77.9300,169.5,20880.0,2625.0
156,2024-01-31,167.57,156.36,184.58,27.0,46.2,1.7954,72.14,69.24,3.31,...,427.23,149.83,141.05,2181.125,8339.375,1580.5,79.9025,169.5,20775.0,2700.0
157,2024-02-29,171.05,159.79,188.13,29.0,54.0,3.0751,73.22,70.23,3.39,...,444.50,157.14,141.65,2187.500,8314.000,1548.5,82.8375,169.5,20925.0,2700.0
158,2024-03-31,173.13,162.66,188.99,30.0,56.4,2.1472,73.51,70.41,3.38,...,492.01,154.33,139.16,2225.500,8664.600,1934.2,86.5420,169.5,20380.0,2700.0

In [47]:
vars_shift_df = time_df.iloc[:,0:2]

In [48]:
vars_shift_df.columns = ['date', 'target_index_house_index_xyi_all_tp']
vars_shift_df

           date  target_index_house_index_xyi_all_tp
0    2011-01-31                                95.40
1    2011-02-28                                97.69
2    2011-03-31                                97.76
3    2011-04-30                                97.31
4    2011-05-31                                96.85
..          ...                                  ...
154  2023-11-30                               162.10
155  2023-12-31                               163.19
156  2024-01-31                               167.57
157  2024-02-29                               171.05
158  2024-03-31                               173.13

[159 rows x 2 columns]

In [49]:
col_vars = time_df.columns.drop('date')
col_vars

Index(['house_index_xyi_all_tp', 'house_index_xyi_tp',
       'house_index_xyi_new_tp', 'EA1101', 'EB0312', 'EB0911', 'EB18', 'EB21',
       'LA07', 'MA1501', 'MB65', 'MC31', 'MC36', 'MO30', 'MP101G', 'NA0101',
       'NA1005', 'NB0101', 'NC0117', 'NC0118', 'NE0206', 'PA0120', 'PA1205',
       'PE0503', 'TSE收盤', '水泥(TSE11)收盤', '建材營造(TSE25)收盤', '航運業(TSE26)收盤',
       '鋼鐵(TSE20)收盤', '倫敦鋁現貨價', '倫敦高級銅極現貨價', '巴拿馬型貨櫃運費指數', '杜拜輕原油現貨價',
       '水泥50kg北區台泥', '竹節鋼筋_南', '預拌混凝土3000磅台北'],
      dtype='object')

In [14]:
# var = 'EA1101'
# for lag in range(1,6,1):
#     one_var_shift_df[f'{var}_lag_{lag}'] = time_df[var].shift(lag)

In [51]:
for eco_name in col_vars:
    print(eco_name)
    var = eco_name
    for lag in range(1,6,1):
        vars_shift_df[f'{var}_lag_{lag}'] = time_df[var].shift(lag)

house_index_xyi_all_tp
house_index_xyi_tp
house_index_xyi_new_tp
EA1101
EB0312
EB0911
EB18
EB21
LA07
MA1501
MB65
MC31
MC36
MO30
MP101G
NA0101
NA1005
NB0101
NC0117
NC0118
NE0206
PA0120
PA1205
PE0503
TSE收盤
水泥(TSE11)收盤
建材營造(TSE25)收盤
航運業(TSE26)收盤
鋼鐵(TSE20)收盤
倫敦鋁現貨價
倫敦高級銅極現貨價
巴拿馬型貨櫃運費指數
杜拜輕原油現貨價
水泥50kg北區台泥
竹節鋼筋_南
預拌混凝土3000磅台北

C:\Users\Tony\AppData\Local\Temp\ipykernel_11296\3340483299.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  vars_shift_df[f'{var}_lag_{lag}'] = time_df[var].shift(lag)
C:\Users\Tony\AppData\Local\Temp\ipykernel_11296\3340483299.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  vars_shift_df[f'{var}_lag_{lag}'] = time_df[var].shift(lag)
C:\Users\Tony\AppData\Local\Temp\ipykernel_11296\3340483299.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  vars_shift_df[f'{var}_lag_{lag}'] = time_df[var].shift(lag)
C:\Users\Tony\AppData\Local\Temp\ipykernel_11296\3340483299.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  vars_shift_df[f'{var}_lag_{lag}'] = time_df[var].shift(lag)
C:\Users\Tony\AppData\Local\Temp\ipykernel_11296\3340483299.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  vars_shift_df[f'{var}_lag_{lag}'] = time_df[var].shift(lag)
C:\Users\Tony\AppData\Local\Temp\ipykernel_11296\3340483299.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  vars_shift_df[f'{var}_lag_{lag}'] = time_df[var].shift(lag)
C:\Users\Tony\AppData\Local\Temp\ipykernel_11296\3340483299.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  vars_shift_df[f'{var}_lag_{lag}'] = time_df[var].shift(lag)
C:\Users\Tony\AppData\Local\Temp\ipykernel_11296\3340483299.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  vars_shift_df[f'{var}_lag_{lag}'] = time_df[var].shift(lag)
C:\Users\Tony\AppData\Local\Temp\ipykernel_11296\3340483299.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  vars_shift_df[f'{var}_lag_{lag}'] = time_df[var].shift(lag)
C:\Users\Tony\AppData\Local\Temp\ipykernel_11296\3340483299.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  vars_shift_df[f'{var}_lag_{lag}'] = time_df[var].shift(lag)
C:\Users\Tony\AppData\Local\Temp\ipykernel_11296\3340483299.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  vars_shift_df[f'{var}_lag_{lag}'] = time_df[var].shift(lag)
C:\Users\Tony\AppData\Local\Temp\ipykernel_11296\3340483299.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  vars_shift_df[f'{var}_lag_{lag}'] = time_df[var].shift(lag)
C:\Users\Tony\AppData\Local\Temp\ipykernel_11296\3340483299.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  vars_shift_df[f'{var}_lag_{lag}'] = time_df[var].shift(lag)
C:\Users\Tony\AppData\Local\Temp\ipykernel_11296\3340483299.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  vars_shift_df[f'{var}_lag_{lag}'] = time_df[var].shift(lag)
C:\Users\Tony\AppData\Local\Temp\ipykernel_11296\3340483299.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  vars_shift_df[f'{var}_lag_{lag}'] = time_df[var].shift(lag)
C:\Users\Tony\AppData\Local\Temp\ipykernel_11296\3340483299.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  vars_shift_df[f'{var}_lag_{lag}'] = time_df[var].shift(lag)
C:\Users\Tony\AppData\Local\Temp\ipykernel_11296\3340483299.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  vars_shift_df[f'{var}_lag_{lag}'] = time_df[var].shift(lag)
C:\Users\Tony\AppData\Local\Temp\ipykernel_11296\3340483299.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  vars_shift_df[f'{var}_lag_{lag}'] = time_df[var].shift(lag)
C:\Users\Tony\AppData\Local\Temp\ipykernel_11296\3340483299.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  vars_shift_df[f'{var}_lag_{lag}'] = time_df[var].shift(lag)
C:\Users\Tony\AppData\Local\Temp\ipykernel_11296\3340483299.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  vars_shift_df[f'{var}_lag_{lag}'] = time_df[var].shift(lag)
C:\Users\Tony\AppData\Local\Temp\ipykernel_11296\3340483299.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  vars_shift_df[f'{var}_lag_{lag}'] = time_df[var].shift(lag)
C:\Users\Tony\AppData\Local\Temp\ipykernel_11296\3340483299.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  vars_shift_df[f'{var}_lag_{lag}'] = time_df[var].shift(lag)
C:\Users\Tony\AppData\Local\Temp\ipykernel_11296\3340483299.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  vars_shift_df[f'{var}_lag_{lag}'] = time_df[var].shift(lag)
C:\Users\Tony\AppData\Local\Temp\ipykernel_11296\3340483299.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  vars_shift_df[f'{var}_lag_{lag}'] = time_df[var].shift(lag)
C:\Users\Tony\AppData\Local\Temp\ipykernel_11296\3340483299.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  vars_shift_df[f'{var}_lag_{lag}'] = time_df[var].shift(lag)
C:\Users\Tony\AppData\Local\Temp\ipykernel_11296\3340483299.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  vars_shift_df[f'{var}_lag_{lag}'] = time_df[var].shift(lag)
C:\Users\Tony\AppData\Local\Temp\ipykernel_11296\3340483299.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  vars_shift_df[f'{var}_lag_{lag}'] = time_df[var].shift(lag)
C:\Users\Tony\AppData\Local\Temp\ipykernel_11296\3340483299.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  vars_shift_df[f'{var}_lag_{lag}'] = time_df[var].shift(lag)
C:\Users\Tony\AppData\Local\Temp\ipykernel_11296\3340483299.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  vars_shift_df[f'{var}_lag_{lag}'] = time_df[var].shift(lag)
C:\Users\Tony\AppData\Local\Temp\ipykernel_11296\3340483299.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  vars_shift_df[f'{var}_lag_{lag}'] = time_df[var].shift(lag)
C:\Users\Tony\AppData\Local\Temp\ipykernel_11296\3340483299.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  vars_shift_df[f'{var}_lag_{lag}'] = time_df[var].shift(lag)
C:\Users\Tony\AppData\Local\Temp\ipykernel_11296\3340483299.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  vars_shift_df[f'{var}_lag_{lag}'] = time_df[var].shift(lag)
C:\Users\Tony\AppData\Local\Temp\ipykernel_11296\3340483299.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  vars_shift_df[f'{var}_lag_{lag}'] = time_df[var].shift(lag)
C:\Users\Tony\AppData\Local\Temp\ipykernel_11296\3340483299.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  vars_shift_df[f'{var}_lag_{lag}'] = time_df[var].shift(lag)
C:\Users\Tony\AppData\Local\Temp\ipykernel_11296\3340483299.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  vars_shift_df[f'{var}_lag_{lag}'] = time_df[var].shift(lag)
C:\Users\Tony\AppData\Local\Temp\ipykernel_11296\3340483299.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  vars_shift_df[f'{var}_lag_{lag}'] = time_df[var].shift(lag)
C:\Users\Tony\AppData\Local\Temp\ipykernel_11296\3340483299.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  vars_shift_df[f'{var}_lag_{lag}'] = time_df[var].shift(lag)
C:\Users\Tony\AppData\Local\Temp\ipykernel_11296\3340483299.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  vars_shift_df[f'{var}_lag_{lag}'] = time_df[var].shift(lag)
C:\Users\Tony\AppData\Local\Temp\ipykernel_11296\3340483299.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  vars_shift_df[f'{var}_lag_{lag}'] = time_df[var].shift(lag)
C:\Users\Tony\AppData\Local\Temp\ipykernel_11296\3340483299.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  vars_shift_df[f'{var}_lag_{lag}'] = time_df[var].shift(lag)
C:\Users\Tony\AppData\Local\Temp\ipykernel_11296\3340483299.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  vars_shift_df[f'{var}_lag_{lag}'] = time_df[var].shift(lag)
C:\Users\Tony\AppData\Local\Temp\ipykernel_11296\3340483299.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  vars_shift_df[f'{var}_lag_{lag}'] = time_df[var].shift(lag)
C:\Users\Tony\AppData\Local\Temp\ipykernel_11296\3340483299.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  vars_shift_df[f'{var}_lag_{lag}'] = time_df[var].shift(lag)
C:\Users\Tony\AppData\Local\Temp\ipykernel_11296\3340483299.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  vars_shift_df[f'{var}_lag_{lag}'] = time_df[var].shift(lag)
C:\Users\Tony\AppData\Local\Temp\ipykernel_11296\3340483299.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  vars_shift_df[f'{var}_lag_{lag}'] = time_df[var].shift(lag)
C:\Users\Tony\AppData\Local\Temp\ipykernel_11296\3340483299.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  vars_shift_df[f'{var}_lag_{lag}'] = time_df[var].shift(lag)
C:\Users\Tony\AppData\Local\Temp\ipykernel_11296\3340483299.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  vars_shift_df[f'{var}_lag_{lag}'] = time_df[var].shift(lag)
C:\Users\Tony\AppData\Local\Temp\ipykernel_11296\3340483299.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  vars_shift_df[f'{var}_lag_{lag}'] = time_df[var].shift(lag)
C:\Users\Tony\AppData\Local\Temp\ipykernel_11296\3340483299.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  vars_shift_df[f'{var}_lag_{lag}'] = time_df[var].shift(lag)

In [81]:
# 原先feature=36，每個要生5個lag值 36*5 +2(date, target_y) = 出來就是182columns
vars_shift_df.info(max_cols=182)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 159 entries, 0 to 158
Data columns (total 182 columns):
 #    Column                               Non-Null Count  Dtype
---   ------                               --------------  -----
 0    date                                 159 non-null    object
 1    target_index_house_index_xyi_all_tp  159 non-null    float64
 2    house_index_xyi_all_tp_lag_1         159 non-null    float64
 3    house_index_xyi_all_tp_lag_2         159 non-null    float64
 4    house_index_xyi_all_tp_lag_3         159 non-null    float64
 5    house_index_xyi_all_tp_lag_4         159 non-null    float64
 6    house_index_xyi_all_tp_lag_5         159 non-null    float64
 7    house_index_xyi_tp_lag_1             159 non-null    float64
 8    house_index_xyi_tp_lag_2             159 non-null    float64
 9    house_index_xyi_tp_lag_3             159 non-null    float64
 10   house_index_xyi_tp_lag_4             159 non-null    float64
 11   house_index_xyi_tp_lag_5             159 non-null    float64
 12   house_index_xyi_new_tp_lag_1         159 non-null    float64
 13   house_index_xyi_new_tp_lag_2         159 non-null    float64
 14   house_index_xyi_new_tp_lag_3         159 non-null    float64
 15   house_index_xyi_new_tp_lag_4         159 non-null    float64
 16   house_index_xyi_new_tp_lag_5         159 non-null    float64
 17   EA1101_lag_1                         159 non-null    float64
 18   EA1101_lag_2                         159 non-null    float64
 19   EA1101_lag_3                         159 non-null    float64
 20   EA1101_lag_4                         159 non-null    float64
 21   EA1101_lag_5                         159 non-null    float64
 22   EB0312_lag_1                         159 non-null    float64
 23   EB0312_lag_2                         159 non-null    float64
 24   EB0312_lag_3                         159 non-null    float64
 25   EB0312_lag_4                         159 non-null    float64
 26   EB0312_lag_5                         159 non-null    float64
 27   EB0911_lag_1                         159 non-null    float64
 28   EB0911_lag_2                         159 non-null    float64
 29   EB0911_lag_3                         159 non-null    float64
 30   EB0911_lag_4                         159 non-null    float64
 31   EB0911_lag_5                         159 non-null    float64
 32   EB18_lag_1                           159 non-null    float64
 33   EB18_lag_2                           159 non-null    float64
 34   EB18_lag_3                           159 non-null    float64
 35   EB18_lag_4                           159 non-null    float64
 36   EB18_lag_5                           159 non-null    float64
 37   EB21_lag_1                           159 non-null    float64
 38   EB21_lag_2                           159 non-null    float64
 39   EB21_lag_3                           159 non-null    float64
 40   EB21_lag_4                           159 non-null    float64
 41   EB21_lag_5                           159 non-null    float64
 42   LA07_lag_1                           159 non-null    float64
 43   LA07_lag_2                           159 non-null    float64
 44   LA07_lag_3                           159 non-null    float64
 45   LA07_lag_4                           159 non-null    float64
 46   LA07_lag_5                           159 non-null    float64
 47   MA1501_lag_1                         159 non-null    float64
 48   MA1501_lag_2                         159 non-null    float64
 49   MA1501_lag_3                         159 non-null    float64
 50   MA1501_lag_4                         159 non-null    float64
 51   MA1501_lag_5                         159 non-null    float64
 52   MB65_lag_1                           159 non-null    float64
 53   MB65_lag_2                           159 non-null    float64
 54   MB65_lag_3                           159 non-null    float64
 55   MB65_lag_4                           159 non-null    float64
 56   MB65_lag_5                           159 non-null    float64
 57   MC31_lag_1                           159 non-null    float64
 58   MC31_lag_2                           159 non-null    float64
 59   MC31_lag_3                           159 non-null    float64
 60   MC31_lag_4                           159 non-null    float64
 61   MC31_lag_5                           159 non-null    float64
 62   MC36_lag_1                           159 non-null    float64
 63   MC36_lag_2                           159 non-null    float64
 64   MC36_lag_3                           159 non-null    float64
 65   MC36_lag_4                           159 non-null    float64
 66   MC36_lag_5                           159 non-null    float64
 67   MO30_lag_1                           159 non-null    float64
 68   MO30_lag_2                           159 non-null    float64
 69   MO30_lag_3                           159 non-null    float64
 70   MO30_lag_4                           159 non-null    float64
 71   MO30_lag_5                           159 non-null    float64
 72   MP101G_lag_1                         159 non-null    float64
 73   MP101G_lag_2                         159 non-null    float64
 74   MP101G_lag_3                         159 non-null    float64
 75   MP101G_lag_4                         159 non-null    float64
 76   MP101G_lag_5                         159 non-null    float64
 77   NA0101_lag_1                         159 non-null    float64
 78   NA0101_lag_2                         159 non-null    float64
 79   NA0101_lag_3                         159 non-null    float64
 80   NA0101_lag_4                         159 non-null    float64
 81   NA0101_lag_5                         159 non-null    float64
 82   NA1005_lag_1                         159 non-null    float64
 83   NA1005_lag_2                         159 non-null    float64
 84   NA1005_lag_3                         159 non-null    float64
 85   NA1005_lag_4                         159 non-null    float64
 86   NA1005_lag_5                         159 non-null    float64
 87   NB0101_lag_1                         159 non-null    float64
 88   NB0101_lag_2                         159 non-null    float64
 89   NB0101_lag_3                         159 non-null    float64
 90   NB0101_lag_4                         159 non-null    float64
 91   NB0101_lag_5                         159 non-null    float64
 92   NC0117_lag_1                         159 non-null    float64
 93   NC0117_lag_2                         159 non-null    float64
 94   NC0117_lag_3                         159 non-null    float64
 95   NC0117_lag_4                         159 non-null    float64
 96   NC0117_lag_5                         159 non-null    float64
 97   NC0118_lag_1                         159 non-null    float64
 98   NC0118_lag_2                         159 non-null    float64
 99   NC0118_lag_3                         159 non-null    float64
 100  NC0118_lag_4                         159 non-null    float64
 101  NC0118_lag_5                         159 non-null    float64
 102  NE0206_lag_1                         159 non-null    float64
 103  NE0206_lag_2                         159 non-null    float64
 104  NE0206_lag_3                         159 non-null    float64
 105  NE0206_lag_4                         159 non-null    float64
 106  NE0206_lag_5                         159 non-null    float64
 107  PA0120_lag_1                         159 non-null    float64
 108  PA0120_lag_2                         159 non-null    float64
 109  PA0120_lag_3                         159 non-null    float64
 110  PA0120_lag_4                         159 non-null    float64
 111  PA0120_lag_5                         159 non-null    float64
 112  PA1205_lag_1                         159 non-null    float64
 113  PA1205_lag_2                         159 non-null    float64
 114  PA1205_lag_3                         159 non-null    float64
 115  PA1205_lag_4                         159 non-null    float64
 116  PA1205_lag_5                         159 non-null    float64
 117  PE0503_lag_1                         159 non-null    float64
 118  PE0503_lag_2                         159 non-null    float64
 119  PE0503_lag_3                         159 non-null    float64
 120  PE0503_lag_4                         159 non-null    float64
 121  PE0503_lag_5                         159 non-null    float64
 122  TSE收盤_lag_1                          159 non-null    float64
 123  TSE收盤_lag_2                          159 non-null    float64
 124  TSE收盤_lag_3                          159 non-null    float64
 125  TSE收盤_lag_4                          159 non-null    float64
 126  TSE收盤_lag_5                          159 non-null    float64
 127  水泥(TSE11)收盤_lag_1                    159 non-null    float64
 128  水泥(TSE11)收盤_lag_2                    159 non-null    float64
 129  水泥(TSE11)收盤_lag_3                    159 non-null    float64
 130  水泥(TSE11)收盤_lag_4                    159 non-null    float64
 131  水泥(TSE11)收盤_lag_5                    159 non-null    float64
 132  建材營造(TSE25)收盤_lag_1                  159 non-null    float64
 133  建材營造(TSE25)收盤_lag_2                  159 non-null    float64
 134  建材營造(TSE25)收盤_lag_3                  159 non-null    float64
 135  建材營造(TSE25)收盤_lag_4                  159 non-null    float64
 136  建材營造(TSE25)收盤_lag_5                  159 non-null    float64
 137  航運業(TSE26)收盤_lag_1                   159 non-null    float64
 138  航運業(TSE26)收盤_lag_2                   159 non-null    float64
 139  航運業(TSE26)收盤_lag_3                   159 non-null    float64
 140  航運業(TSE26)收盤_lag_4                   159 non-null    float64
 141  航運業(TSE26)收盤_lag_5                   159 non-null    float64
 142  鋼鐵(TSE20)收盤_lag_1                    159 non-null    float64
 143  鋼鐵(TSE20)收盤_lag_2                    159 non-null    float64
 144  鋼鐵(TSE20)收盤_lag_3                    159 non-null    float64
 145  鋼鐵(TSE20)收盤_lag_4                    159 non-null    float64
 146  鋼鐵(TSE20)收盤_lag_5                    159 non-null    float64
 147  倫敦鋁現貨價_lag_1                         159 non-null    float64
 148  倫敦鋁現貨價_lag_2                         159 non-null    float64
 149  倫敦鋁現貨價_lag_3                         159 non-null    float64
 150  倫敦鋁現貨價_lag_4                         159 non-null    float64
 151  倫敦鋁現貨價_lag_5                         159 non-null    float64
 152  倫敦高級銅極現貨價_lag_1                      159 non-null    float64
 153  倫敦高級銅極現貨價_lag_2                      159 non-null    float64
 154  倫敦高級銅極現貨價_lag_3                      159 non-null    float64
 155  倫敦高級銅極現貨價_lag_4                      159 non-null    float64
 156  倫敦高級銅極現貨價_lag_5                      159 non-null    float64
 157  巴拿馬型貨櫃運費指數_lag_1                     159 non-null    float64
 158  巴拿馬型貨櫃運費指數_lag_2                     159 non-null    float64
 159  巴拿馬型貨櫃運費指數_lag_3                     159 non-null    float64
 160  巴拿馬型貨櫃運費指數_lag_4                     159 non-null    float64
 161  巴拿馬型貨櫃運費指數_lag_5                     159 non-null    float64
 162  杜拜輕原油現貨價_lag_1                       159 non-null    float64
 163  杜拜輕原油現貨價_lag_2                       159 non-null    float64
 164  杜拜輕原油現貨價_lag_3                       159 non-null    float64
 165  杜拜輕原油現貨價_lag_4                       159 non-null    float64
 166  杜拜輕原油現貨價_lag_5                       159 non-null    float64
 167  水泥50kg北區台泥_lag_1                     159 non-null    float64
 168  水泥50kg北區台泥_lag_2                     159 non-null    float64
 169  水泥50kg北區台泥_lag_3                     159 non-null    float64
 170  水泥50kg北區台泥_lag_4                     159 non-null    float64
 171  水泥50kg北區台泥_lag_5                     159 non-null    float64
 172  竹節鋼筋_南_lag_1                         159 non-null    float64
 173  竹節鋼筋_南_lag_2                         159 non-null    float64
 174  竹節鋼筋_南_lag_3                         159 non-null    float64
 175  竹節鋼筋_南_lag_4                         159 non-null    float64
 176  竹節鋼筋_南_lag_5                         159 non-null    float64
 177  預拌混凝土3000磅台北_lag_1                   159 non-null    float64
 178  預拌混凝土3000磅台北_lag_2                   159 non-null    float64
 179  預拌混凝土3000磅台北_lag_3                   159 non-null    float64
 180  預拌混凝土3000磅台北_lag_4                   159 non-null    float64
 181  預拌混凝土3000磅台北_lag_5                   159 non-null    float64
dtypes: float64(181), object(1)
memory usage: 226.2+ KB

In [54]:
vars_shift_df.info(max_cols=222)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 159 entries, 0 to 158
Data columns (total 182 columns):
 #    Column                               Non-Null Count  Dtype
---   ------                               --------------  -----
 0    date                                 159 non-null    object
 1    target_index_house_index_xyi_all_tp  159 non-null    float64
 2    house_index_xyi_all_tp_lag_1         158 non-null    float64
 3    house_index_xyi_all_tp_lag_2         157 non-null    float64
 4    house_index_xyi_all_tp_lag_3         156 non-null    float64
 5    house_index_xyi_all_tp_lag_4         155 non-null    float64
 6    house_index_xyi_all_tp_lag_5         154 non-null    float64
 7    house_index_xyi_tp_lag_1             158 non-null    float64
 8    house_index_xyi_tp_lag_2             157 non-null    float64
 9    house_index_xyi_tp_lag_3             156 non-null    float64
 10   house_index_xyi_tp_lag_4             155 non-null    float64
 11   house_index_xyi_tp_lag_5             154 non-null    float64
 12   house_index_xyi_new_tp_lag_1         158 non-null    float64
 13   house_index_xyi_new_tp_lag_2         157 non-null    float64
 14   house_index_xyi_new_tp_lag_3         156 non-null    float64
 15   house_index_xyi_new_tp_lag_4         155 non-null    float64
 16   house_index_xyi_new_tp_lag_5         154 non-null    float64
 17   EA1101_lag_1                         158 non-null    float64
 18   EA1101_lag_2                         157 non-null    float64
 19   EA1101_lag_3                         156 non-null    float64
 20   EA1101_lag_4                         155 non-null    float64
 21   EA1101_lag_5                         154 non-null    float64
 22   EB0312_lag_1                         158 non-null    float64
 23   EB0312_lag_2                         157 non-null    float64
 24   EB0312_lag_3                         156 non-null    float64
 25   EB0312_lag_4                         155 non-null    float64
 26   EB0312_lag_5                         154 non-null    float64
 27   EB0911_lag_1                         158 non-null    float64
 28   EB0911_lag_2                         157 non-null    float64
 29   EB0911_lag_3                         156 non-null    float64
 30   EB0911_lag_4                         155 non-null    float64
 31   EB0911_lag_5                         154 non-null    float64
 32   EB18_lag_1                           158 non-null    float64
 33   EB18_lag_2                           157 non-null    float64
 34   EB18_lag_3                           156 non-null    float64
 35   EB18_lag_4                           155 non-null    float64
 36   EB18_lag_5                           154 non-null    float64
 37   EB21_lag_1                           158 non-null    float64
 38   EB21_lag_2                           157 non-null    float64
 39   EB21_lag_3                           156 non-null    float64
 40   EB21_lag_4                           155 non-null    float64
 41   EB21_lag_5                           154 non-null    float64
 42   LA07_lag_1                           158 non-null    float64
 43   LA07_lag_2                           157 non-null    float64
 44   LA07_lag_3                           156 non-null    float64
 45   LA07_lag_4                           155 non-null    float64
 46   LA07_lag_5                           154 non-null    float64
 47   MA1501_lag_1                         158 non-null    float64
 48   MA1501_lag_2                         157 non-null    float64
 49   MA1501_lag_3                         156 non-null    float64
 50   MA1501_lag_4                         155 non-null    float64
 51   MA1501_lag_5                         154 non-null    float64
 52   MB65_lag_1                           158 non-null    float64
 53   MB65_lag_2                           157 non-null    float64
 54   MB65_lag_3                           156 non-null    float64
 55   MB65_lag_4                           155 non-null    float64
 56   MB65_lag_5                           154 non-null    float64
 57   MC31_lag_1                           158 non-null    float64
 58   MC31_lag_2                           157 non-null    float64
 59   MC31_lag_3                           156 non-null    float64
 60   MC31_lag_4                           155 non-null    float64
 61   MC31_lag_5                           154 non-null    float64
 62   MC36_lag_1                           158 non-null    float64
 63   MC36_lag_2                           157 non-null    float64
 64   MC36_lag_3                           156 non-null    float64
 65   MC36_lag_4                           155 non-null    float64
 66   MC36_lag_5                           154 non-null    float64
 67   MO30_lag_1                           158 non-null    float64
 68   MO30_lag_2                           157 non-null    float64
 69   MO30_lag_3                           156 non-null    float64
 70   MO30_lag_4                           155 non-null    float64
 71   MO30_lag_5                           154 non-null    float64
 72   MP101G_lag_1                         158 non-null    float64
 73   MP101G_lag_2                         157 non-null    float64
 74   MP101G_lag_3                         156 non-null    float64
 75   MP101G_lag_4                         155 non-null    float64
 76   MP101G_lag_5                         154 non-null    float64
 77   NA0101_lag_1                         158 non-null    float64
 78   NA0101_lag_2                         157 non-null    float64
 79   NA0101_lag_3                         156 non-null    float64
 80   NA0101_lag_4                         155 non-null    float64
 81   NA0101_lag_5                         154 non-null    float64
 82   NA1005_lag_1                         158 non-null    float64
 83   NA1005_lag_2                         157 non-null    float64
 84   NA1005_lag_3                         156 non-null    float64
 85   NA1005_lag_4                         155 non-null    float64
 86   NA1005_lag_5                         154 non-null    float64
 87   NB0101_lag_1                         158 non-null    float64
 88   NB0101_lag_2                         157 non-null    float64
 89   NB0101_lag_3                         156 non-null    float64
 90   NB0101_lag_4                         155 non-null    float64
 91   NB0101_lag_5                         154 non-null    float64
 92   NC0117_lag_1                         158 non-null    float64
 93   NC0117_lag_2                         157 non-null    float64
 94   NC0117_lag_3                         156 non-null    float64
 95   NC0117_lag_4                         155 non-null    float64
 96   NC0117_lag_5                         154 non-null    float64
 97   NC0118_lag_1                         158 non-null    float64
 98   NC0118_lag_2                         157 non-null    float64
 99   NC0118_lag_3                         156 non-null    float64
 100  NC0118_lag_4                         155 non-null    float64
 101  NC0118_lag_5                         154 non-null    float64
 102  NE0206_lag_1                         158 non-null    float64
 103  NE0206_lag_2                         157 non-null    float64
 104  NE0206_lag_3                         156 non-null    float64
 105  NE0206_lag_4                         155 non-null    float64
 106  NE0206_lag_5                         154 non-null    float64
 107  PA0120_lag_1                         158 non-null    float64
 108  PA0120_lag_2                         157 non-null    float64
 109  PA0120_lag_3                         156 non-null    float64
 110  PA0120_lag_4                         155 non-null    float64
 111  PA0120_lag_5                         154 non-null    float64
 112  PA1205_lag_1                         158 non-null    float64
 113  PA1205_lag_2                         157 non-null    float64
 114  PA1205_lag_3                         156 non-null    float64
 115  PA1205_lag_4                         155 non-null    float64
 116  PA1205_lag_5                         154 non-null    float64
 117  PE0503_lag_1                         158 non-null    float64
 118  PE0503_lag_2                         157 non-null    float64
 119  PE0503_lag_3                         156 non-null    float64
 120  PE0503_lag_4                         155 non-null    float64
 121  PE0503_lag_5                         154 non-null    float64
 122  TSE收盤_lag_1                          158 non-null    float64
 123  TSE收盤_lag_2                          157 non-null    float64
 124  TSE收盤_lag_3                          156 non-null    float64
 125  TSE收盤_lag_4                          155 non-null    float64
 126  TSE收盤_lag_5                          154 non-null    float64
 127  水泥(TSE11)收盤_lag_1                    158 non-null    float64
 128  水泥(TSE11)收盤_lag_2                    157 non-null    float64
 129  水泥(TSE11)收盤_lag_3                    156 non-null    float64
 130  水泥(TSE11)收盤_lag_4                    155 non-null    float64
 131  水泥(TSE11)收盤_lag_5                    154 non-null    float64
 132  建材營造(TSE25)收盤_lag_1                  158 non-null    float64
 133  建材營造(TSE25)收盤_lag_2                  157 non-null    float64
 134  建材營造(TSE25)收盤_lag_3                  156 non-null    float64
 135  建材營造(TSE25)收盤_lag_4                  155 non-null    float64
 136  建材營造(TSE25)收盤_lag_5                  154 non-null    float64
 137  航運業(TSE26)收盤_lag_1                   158 non-null    float64
 138  航運業(TSE26)收盤_lag_2                   157 non-null    float64
 139  航運業(TSE26)收盤_lag_3                   156 non-null    float64
 140  航運業(TSE26)收盤_lag_4                   155 non-null    float64
 141  航運業(TSE26)收盤_lag_5                   154 non-null    float64
 142  鋼鐵(TSE20)收盤_lag_1                    158 non-null    float64
 143  鋼鐵(TSE20)收盤_lag_2                    157 non-null    float64
 144  鋼鐵(TSE20)收盤_lag_3                    156 non-null    float64
 145  鋼鐵(TSE20)收盤_lag_4                    155 non-null    float64
 146  鋼鐵(TSE20)收盤_lag_5                    154 non-null    float64
 147  倫敦鋁現貨價_lag_1                         158 non-null    float64
 148  倫敦鋁現貨價_lag_2                         157 non-null    float64
 149  倫敦鋁現貨價_lag_3                         156 non-null    float64
 150  倫敦鋁現貨價_lag_4                         155 non-null    float64
 151  倫敦鋁現貨價_lag_5                         154 non-null    float64
 152  倫敦高級銅極現貨價_lag_1                      158 non-null    float64
 153  倫敦高級銅極現貨價_lag_2                      157 non-null    float64
 154  倫敦高級銅極現貨價_lag_3                      156 non-null    float64
 155  倫敦高級銅極現貨價_lag_4                      155 non-null    float64
 156  倫敦高級銅極現貨價_lag_5                      154 non-null    float64
 157  巴拿馬型貨櫃運費指數_lag_1                     158 non-null    float64
 158  巴拿馬型貨櫃運費指數_lag_2                     157 non-null    float64
 159  巴拿馬型貨櫃運費指數_lag_3                     156 non-null    float64
 160  巴拿馬型貨櫃運費指數_lag_4                     155 non-null    float64
 161  巴拿馬型貨櫃運費指數_lag_5                     154 non-null    float64
 162  杜拜輕原油現貨價_lag_1                       158 non-null    float64
 163  杜拜輕原油現貨價_lag_2                       157 non-null    float64
 164  杜拜輕原油現貨價_lag_3                       156 non-null    float64
 165  杜拜輕原油現貨價_lag_4                       155 non-null    float64
 166  杜拜輕原油現貨價_lag_5                       154 non-null    float64
 167  水泥50kg北區台泥_lag_1                     158 non-null    float64
 168  水泥50kg北區台泥_lag_2                     157 non-null    float64
 169  水泥50kg北區台泥_lag_3                     156 non-null    float64
 170  水泥50kg北區台泥_lag_4                     155 non-null    float64
 171  水泥50kg北區台泥_lag_5                     154 non-null    float64
 172  竹節鋼筋_南_lag_1                         158 non-null    float64
 173  竹節鋼筋_南_lag_2                         157 non-null    float64
 174  竹節鋼筋_南_lag_3                         156 non-null    float64
 175  竹節鋼筋_南_lag_4                         155 non-null    float64
 176  竹節鋼筋_南_lag_5                         154 non-null    float64
 177  預拌混凝土3000磅台北_lag_1                   158 non-null    float64
 178  預拌混凝土3000磅台北_lag_2                   157 non-null    float64
 179  預拌混凝土3000磅台北_lag_3                   156 non-null    float64
 180  預拌混凝土3000磅台北_lag_4                   155 non-null    float64
 181  預拌混凝土3000磅台北_lag_5                   154 non-null    float64
dtypes: float64(181), object(1)
memory usage: 226.2+ KB

In [55]:
vars_shift_df.isnull().sum().sum()

540

In [56]:
vars_shift_df.head(5)

,date,target_index_house_index_xyi_all_tp,house_index_xyi_all_tp_lag_1,house_index_xyi_all_tp_lag_2,house_index_xyi_all_tp_lag_3,house_index_xyi_all_tp_lag_4,house_index_xyi_all_tp_lag_5,house_index_xyi_tp_lag_1,house_index_xyi_tp_lag_2,house_index_xyi_tp_lag_3,...,竹節鋼筋_南_lag_1,竹節鋼筋_南_lag_2,竹節鋼筋_南_lag_3,竹節鋼筋_南_lag_4,竹節鋼筋_南_lag_5,預拌混凝土3000磅台北_lag_1,預拌混凝土3000磅台北_lag_2,預拌混凝土3000磅台北_lag_3,預拌混凝土3000磅台北_lag_4,預拌混凝土3000磅台北_lag_5
0,2011-01-31,95.40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2011-02-28,97.69,95.40,NaN,NaN,NaN,NaN,94.45,NaN,NaN,...,21260.0,NaN,NaN,NaN,NaN,1815.0,NaN,NaN,NaN,NaN
2,2011-03-31,97.76,97.69,95.40,NaN,NaN,NaN,97.34,94.45,NaN,...,21250.0,21260.0,NaN,NaN,NaN,1890.0,1815.0,NaN,NaN,NaN
3,2011-04-30,97.31,97.76,97.69,95.40,NaN,NaN,97.86,97.34,94.45,...,21525.0,21250.0,21260.0,NaN,NaN,1890.0,1890.0,1815.0,NaN,NaN
4,2011-05-31,96.85,97.31,97.76,97.69,95.4,NaN,98.38,97.86,97.34,...,20500.0,21525.0,21250.0,21260.0,NaN,1896.0,1890.0,1890.0,1815.0,NaN

In [57]:
vars_shift_df.fillna(method='bfill', inplace=True)

C:\Users\Tony\AppData\Local\Temp\ipykernel_11296\1132041741.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  vars_shift_df.fillna(method='bfill', inplace=True)

In [58]:
vars_shift_df.head(5)

,date,target_index_house_index_xyi_all_tp,house_index_xyi_all_tp_lag_1,house_index_xyi_all_tp_lag_2,house_index_xyi_all_tp_lag_3,house_index_xyi_all_tp_lag_4,house_index_xyi_all_tp_lag_5,house_index_xyi_tp_lag_1,house_index_xyi_tp_lag_2,house_index_xyi_tp_lag_3,...,竹節鋼筋_南_lag_1,竹節鋼筋_南_lag_2,竹節鋼筋_南_lag_3,竹節鋼筋_南_lag_4,竹節鋼筋_南_lag_5,預拌混凝土3000磅台北_lag_1,預拌混凝土3000磅台北_lag_2,預拌混凝土3000磅台北_lag_3,預拌混凝土3000磅台北_lag_4,預拌混凝土3000磅台北_lag_5
0,2011-01-31,95.40,95.40,95.40,95.40,95.4,95.4,94.45,94.45,94.45,...,21260.0,21260.0,21260.0,21260.0,21260.0,1815.0,1815.0,1815.0,1815.0,1815.0
1,2011-02-28,97.69,95.40,95.40,95.40,95.4,95.4,94.45,94.45,94.45,...,21260.0,21260.0,21260.0,21260.0,21260.0,1815.0,1815.0,1815.0,1815.0,1815.0
2,2011-03-31,97.76,97.69,95.40,95.40,95.4,95.4,97.34,94.45,94.45,...,21250.0,21260.0,21260.0,21260.0,21260.0,1890.0,1815.0,1815.0,1815.0,1815.0
3,2011-04-30,97.31,97.76,97.69,95.40,95.4,95.4,97.86,97.34,94.45,...,21525.0,21250.0,21260.0,21260.0,21260.0,1890.0,1890.0,1815.0,1815.0,1815.0
4,2011-05-31,96.85,97.31,97.76,97.69,95.4,95.4,98.38,97.86,97.34,...,20500.0,21525.0,21250.0,21260.0,21260.0,1896.0,1890.0,1890.0,1815.0,1815.0

In [60]:
# 填na
vars_shift_df.isnull().sum().sum()

0

In [61]:
vars_shift_df.iloc[:,0:6]

,date,target_index_house_index_xyi_all_tp,house_index_xyi_all_tp_lag_1,house_index_xyi_all_tp_lag_2,house_index_xyi_all_tp_lag_3,house_index_xyi_all_tp_lag_4
0,2011-01-31,95.40,95.40,95.40,95.40,95.40
1,2011-02-28,97.69,95.40,95.40,95.40,95.40
2,2011-03-31,97.76,97.69,95.40,95.40,95.40
3,2011-04-30,97.31,97.76,97.69,95.40,95.40
4,2011-05-31,96.85,97.31,97.76,97.69,95.40
...,...,...,...,...,...,...
154,2023-11-30,162.10,161.34,159.85,159.89,155.69
155,2023-12-31,163.19,162.10,161.34,159.85,159.89
156,2024-01-31,167.57,163.19,162.10,161.34,159.85
157,2024-02-29,171.05,167.57,163.19,162.10,161.34
158,2024-03-31,173.13,171.05,167.57,163.19,162.10

## 把每一筆時間的，特徵資料變成二維的
* 原先 X .shape = (180,) -> 更新後 X_new.shape = (5, 36)

In [ ]:
# 有喔~老師有說過怎麼把一條(1D)變成成2D
# 都先從最小的軸開始做axis=0
# 所以若原先形狀為 X = [x_1_lag_1   x_1_lag_2  x_2_lag_1  x_2_lag_2   x_3_lag_1  x_3_lag_2]

# 第一步axis=0代表的是timestamp(此次中有2個)所以形狀就會被切成，axis=0切兩分的意思就是把把原先的一長條切成兩分(等分)，這樣axis=0軸的數量就會等於2

## 這邊形狀寫錯了(寫反了) 應該是
'''
# [[x_1_lag_1   x_2_lag_1  x_3_lag_1],  
   [x_1_lag_2   x_2_lag_2  x_3_lag_2]]

'''


####
'''
# [[x_1_lag_1   x_1_lag_2  x_2_lag_1],  
   [x_2_lag_2   x_3_lag_1  x_3_lag_2]]
'''
# 將特徵轉換為所需的形狀 (2, 3)
# new_X = X.reshape(2, 3)

In [80]:
one_data = vars_shift_df.drop('date', axis=1)
one_data = one_data.iloc[0]

# # target_y就是預測值
y = one_data['target_index_house_index_xyi_all_tp']
# # 所以對於多變量時間序列特徵而言
X = one_data.drop('target_index_house_index_xyi_all_tp')
# # 此時X的shpae應該為 
print(f"X shape:{X.shape}") # 180是有16個特徵，每個有5個lag

new_X = X.values.reshape(5,36)
print(f"new_X shape:{new_X.shape}")
print('='*50)

print(f"{X}")

print(f"{new_X}")

X shape:(180,)
new_X shape:(5, 36)
==================================================
house_index_xyi_all_tp_lag_1      95.4
house_index_xyi_all_tp_lag_2      95.4
house_index_xyi_all_tp_lag_3      95.4
house_index_xyi_all_tp_lag_4      95.4
house_index_xyi_all_tp_lag_5      95.4
                                 ...
預拌混凝土3000磅台北_lag_1              1815.0
預拌混凝土3000磅台北_lag_2              1815.0
預拌混凝土3000磅台北_lag_3              1815.0
預拌混凝土3000磅台北_lag_4              1815.0
預拌混凝土3000磅台北_lag_5              1815.0
Name: 0, Length: 180, dtype: float64
[[9.5400000e+01 9.5400000e+01 9.5400000e+01 9.5400000e+01 9.5400000e+01
  9.4450000e+01 9.4450000e+01 9.4450000e+01 9.4450000e+01 9.4450000e+01
  9.6840000e+01 9.6840000e+01 9.6840000e+01 9.6840000e+01 9.6840000e+01
  3.4000000e+01 3.4000000e+01 3.4000000e+01 3.4000000e+01 3.4000000e+01
  2.8800000e+01 2.8800000e+01 2.8800000e+01 2.8800000e+01 2.8800000e+01
  1.0978000e+00 1.0978000e+00 1.0978000e+00 1.0978000e+00 1.0978000e+00
  8.6780000e+01 8.6780000e+01 8.6780000e+01 8.6780000e+01 8.6780000e+01
  9.5850000e+01]
 [9.5850000e+01 9.5850000e+01 9.5850000e+01 9.5850000e+01 4.6400000e+00
  4.6400000e+00 4.6400000e+00 4.6400000e+00 4.6400000e+00 5.6268000e+00
  5.6268000e+00 5.6268000e+00 5.6268000e+00 5.6268000e+00 1.1900000e+00
  1.1900000e+00 1.1900000e+00 1.1900000e+00 1.1900000e+00 5.1385970e+06
  5.1385970e+06 5.1385970e+06 5.1385970e+06 5.1385970e+06 1.2590980e+06
  1.2590980e+06 1.2590980e+06 1.2590980e+06 1.2590980e+06 1.7600000e+00
  1.7600000e+00 1.7600000e+00 1.7600000e+00 1.7600000e+00 5.7181000e+00
  5.7181000e+00]
 [5.7181000e+00 5.7181000e+00 5.7181000e+00 3.5523290e+06 3.5523290e+06
  3.5523290e+06 3.5523290e+06 3.5523290e+06 3.0254400e+05 3.0254400e+05
  3.0254400e+05 3.0254400e+05 3.0254400e+05 3.7076840e+06 3.7076840e+06
  3.7076840e+06 3.7076840e+06 3.7076840e+06 3.8753660e+06 3.8753660e+06
  3.8753660e+06 3.8753660e+06 3.8753660e+06 3.7022590e+06 3.7022590e+06
  3.7022590e+06 3.7022590e+06 3.7022590e+06 1.5329700e+05 1.5329700e+05
  1.5329700e+05 1.5329700e+05 1.5329700e+05 9.0250000e+01 9.0250000e+01
  9.0250000e+01]
 [9.0250000e+01 9.0250000e+01 2.3911000e+04 2.3911000e+04 2.3911000e+04
  2.3911000e+04 2.3911000e+04 8.3350000e+01 8.3350000e+01 8.3350000e+01
  8.3350000e+01 8.3350000e+01 8.9707585e+03 8.9707585e+03 8.9707585e+03
  8.9707585e+03 8.9707585e+03 1.0981000e+02 1.0981000e+02 1.0981000e+02
  1.0981000e+02 1.0981000e+02 3.4710000e+02 3.4710000e+02 3.4710000e+02
  3.4710000e+02 3.4710000e+02 1.2349000e+02 1.2349000e+02 1.2349000e+02
  1.2349000e+02 1.2349000e+02 1.2070000e+02 1.2070000e+02 1.2070000e+02
  1.2070000e+02]
 [1.2070000e+02 2.4503000e+03 2.4503000e+03 2.4503000e+03 2.4503000e+03
  2.4503000e+03 9.5609000e+03 9.5609000e+03 9.5609000e+03 9.5609000e+03
  9.5609000e+03 1.7382000e+03 1.7382000e+03 1.7382000e+03 1.7382000e+03
  1.7382000e+03 9.1670000e+01 9.1670000e+01 9.1670000e+01 9.1670000e+01
  9.1670000e+01 1.5150000e+02 1.5150000e+02 1.5150000e+02 1.5150000e+02
  1.5150000e+02 2.1260000e+04 2.1260000e+04 2.1260000e+04 2.1260000e+04
  2.1260000e+04 1.8150000e+03 1.8150000e+03 1.8150000e+03 1.8150000e+03
  1.8150000e+03]]

In [71]:
one_data

target_index_house_index_xyi_all_tp      95.4
house_index_xyi_all_tp_lag_1             95.4
house_index_xyi_all_tp_lag_2             95.4
house_index_xyi_all_tp_lag_3             95.4
house_index_xyi_all_tp_lag_4             95.4
                                        ...
預拌混凝土3000磅台北_lag_1                     1815.0
預拌混凝土3000磅台北_lag_2                     1815.0
預拌混凝土3000磅台北_lag_3                     1815.0
預拌混凝土3000磅台北_lag_4                     1815.0
預拌混凝土3000磅台北_lag_5                     1815.0
Name: 0, Length: 181, dtype: float64

##  全部表格的實作
兩種方法
    1. 先每隔都處理好再並到總表
    2. 先並到總表再作此操作